### ISSUE TITLE
No visualization result showing

### ISSUE THREAD

**Issue by darwin-lau** [P7h/StormTweetsSentimentD3Viz#2]
Hi, I love your fantastic tutorial on this!
I downloaded this project, and run it in local mode.
When I click the button "start viz", there is no result showing.
The developer console in Chrome shows the websocket is pending.
May I know how to solve this problem? Thanks.

**Comment by P7h** [comment]
README has detailed documentation with elaborate steps and prerequisites for the execution.
Hope you followed all the steps detailed in the README of the project.
More so the steps under [Configuration](https://github.com/P7h/StormTweetsSentimentD3Viz#configuration) section.

For execution of the code, please refer to the steps mentioned for the [local mode](https://github.com/P7h/StormTweetsSentimentD3Viz#local-mode).

If your configuration and execution is all fine, then when you click on "Start Viz", the visualization of the tweets and sentiments will start.

**Comment by P7h** [comment]
Hi,

Please could you let me know if you were able to run the code successfully.

Thanks,
Prashanth.
